#!/usr/bin/env node
/**
 * Builds the static preview site Netlify publishes (site/):
 *   /forever-crm/?company=4&tab=…   every captured screen, with Design 4.0
 *   /wp-content/plugins/…/assets/   the plugin's own CSS/JS/images
 *   /fx/                            Design 4.0 (from dist/)
 * Screens are chosen by query string through Netlify rewrites in
 * site/_redirects, so the CRM's real links work unchanged.
 * Run after redesign/build.mjs:  node tools/build-site.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const site = path.join(repo, 'site');
const demo = path.join(repo, 'demo');
fs.rmSync(site, { recursive: true, force: true });
fs.mkdirSync(path.join(site, 's'), { recursive: true });

fs.cpSync(path.join(repo, 'plugin', 'assets'), path.join(site, 'wp-content', 'plugins', 'forever-agency-crm-3.2.08', 'assets'), { recursive: true });
fs.cpSync(path.join(repo, 'dist', 'mu-plugins', 'forever-crm-design'), path.join(site, 'fx'), { recursive: true });
if (fs.existsSync(path.join(demo, 'media'))) fs.cpSync(path.join(demo, 'media'), path.join(site, 'media'), { recursive: true });
if (fs.existsSync(path.join(demo, 'manifest.webmanifest'))) fs.copyFileSync(path.join(demo, 'manifest.webmanifest'), path.join(site, 'manifest.webmanifest'));

const tags = '<link rel="stylesheet" href="/fx/design-400.css"><script src="/fx/design-400.js" defer></script>';
const { screens } = JSON.parse(fs.readFileSync(path.join(demo, 'index.json'), 'utf8'));
for (const s of screens) {
  let html = fs.readFileSync(path.join(demo, 'screens', s.file), 'utf8')
    .replace(/href="\/\?fagcrm_manifest=1"/g, 'href="/manifest.webmanifest"');
  const i = html.toLowerCase().lastIndexOf('</head>');
  html = html.slice(0, i) + tags + html.slice(i);
  fs.writeFileSync(path.join(site, 's', s.file), html);
}

// Most specific screens first; Netlify uses the first rule that matches.
const rules = screens
  .map((s) => [s.file, [...new URLSearchParams(s.key)]]);

// Netlify query-string rewrites only match an exact parameter set, and every
// CRM link carries extra ones (company, view, filters), so a small router
// page chooses the screen in the browser and keeps the query string, which
// the CRM scripts and Design 4.0 both read.
const router = `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>My Forever CRM</title>
<meta name="viewport" content="width=device-width, initial-scale=1"><style>html{background:#f5f5f7}</style><script>
(function () {
  var screens = ${JSON.stringify(rules)};
  var q = new URLSearchParams(location.search);
  if (!q.get('company')) q.set('company', '4');
  if (!q.get('tab')) q.set('tab', 'overview');
  var best = null, bestScore = -1;
  screens.forEach(function (s) {
    var ok = true, score = 0;
    s[1].forEach(function (kv) { if (q.get(kv[0]) === kv[1]) score += 1; else ok = false; });
    if (ok && score > bestScore) { best = s[0]; bestScore = score; }
  });
  location.replace('/s/' + (best || 'overview.html') + '?' + q.toString() + location.hash);
})();
</script></head><body></body></html>
`;
fs.mkdirSync(path.join(site, 'forever-crm'), { recursive: true });
fs.writeFileSync(path.join(site, 'forever-crm', 'index.html'), router);
fs.writeFileSync(path.join(site, 'index.html'), router);
fs.writeFileSync(path.join(site, '_redirects'), [
  '# Generated by tools/build-site.mjs',
  '/forever-crm /forever-crm/ 301',
  '/wp-admin/* /404.html 404',
  '/wp-login.php /404.html 404'
].join('\n') + '\n');

fs.writeFileSync(path.join(site, '404.html'), `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>Preview only · My Forever CRM</title>
<style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f5f5f7;color:#1d1d1f;
font:15px/1.5 -apple-system,BlinkMacSystemFont,"SF Pro Text","Segoe UI",Roboto,sans-serif}
main{max-width:420px;padding:32px;text-align:center}h1{font-size:28px;letter-spacing:-.02em;margin:0 0 8px}
p{color:#6e6e73;margin:0 0 20px}a{display:inline-block;padding:10px 18px;border-radius:999px;background:#1d1d1f;color:#fff;text-decoration:none;font-weight:600}</style>
</head><body><main><h1>Preview only</h1><p>This is a design preview of My Forever CRM. Saving, signing in and other server actions are turned off here.</p>
<a href="/forever-crm/?company=4&amp;tab=overview">Back to the dashboard</a></main></body></html>
`);

console.log(`site/: ${screens.length} screens + router`);
